In [ ]:
# Understanding & Cleaning the Dataset #1
# https://www.kaggle.com/datasets/sl6149/data-scientist-job-market-in-the-us

In [6]:
import pandas as pd
import numpy as np

In [7]:
jobs = pd.read_csv('../data/alldata.csv')
# Importing the dataset

In [ ]:
jobs.head()
# Checking the first few rows of the dataset

,position,company,description,reviews,location
0,Development Director,ALS TDI,Development Director\nALS Therapy Development ...,NaN,"Atlanta, GA 30301"
1,An Ostentatiously-Excitable Principal Research...,The Hexagon Lavish,"Job Description\n\n""The road that leads to acc...",NaN,"Atlanta, GA"
2,Data Scientist,Xpert Staffing,"Growing company located in the Atlanta, GA are...",NaN,"Atlanta, GA"
3,Data Analyst,Operation HOPE,DEPARTMENT: Program OperationsPOSITION LOCATIO...,44.0,"Atlanta, GA 30303"
4,Assistant Professor -TT - Signal Processing & ...,Emory University,DESCRIPTION\nThe Emory University Department o...,550.0,"Atlanta, GA"

In [ ]:
jobs.shape
# Checking the shape of the dataset- number of rows and columns

(6964, 5)

In [ ]:
jobs.info()
# Checking the data types of each column and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 6964 entries, 0 to 6963
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   position     6953 non-null   str
 1   company      6953 non-null   str
 2   description  6953 non-null   str
 3   reviews      5326 non-null   float64
 4   location     6953 non-null   str
dtypes: float64(1), str(4)
memory usage: 272.2 KB

In [ ]:
jobs.isnull().sum()
# How many missing values are there in each column?

position         11
company          11
description      11
reviews        1638
location         11
dtype: int64

In [ ]:
jobs[jobs["position"].isnull()]
# Checking the rows where the "position" column has missing values

     position company description  reviews location
302       NaN     NaN         NaN      NaN      NaN
331       NaN     NaN         NaN      NaN      NaN
466       NaN     NaN         NaN      NaN      NaN
482       NaN     NaN         NaN      NaN      NaN
3337      NaN     NaN         NaN      NaN      NaN
5014      NaN     NaN         NaN      NaN      NaN
5059      NaN     NaN         NaN      NaN      NaN
5103      NaN     NaN         NaN      NaN      NaN
5114      NaN     NaN         NaN      NaN      NaN
6093      NaN     NaN         NaN      NaN      NaN
6168      NaN     NaN         NaN      NaN      NaN

In [ ]:
jobs = jobs.dropna(how='all')
# Getting rid of rows where all values are missing

In [ ]:
jobs.shape
# Double-checking the shape of the dataset after dropping rows

(6953, 5)

In [ ]:
jobs['position'].value_counts().head(20)
# The most common job positions in the dataset

position
Data Scientist                         351
Senior Data Scientist                   96
Research Analyst                        64
Data Engineer                           60
Machine Learning Engineer               56
Lead Data Scientist                     31
Research Scientist                      30
Sr. Data Scientist                      28
Principal Data Scientist                24
Data Analyst                            22
Software Engineer                       22
Quantitative Analyst                    21
Scientist                               17
Product Manager                         17
Bioinformatics Scientist                16
Market Research Analyst                 15
Senior Software Engineer                14
Machine Learning Scientist              13
Software Engineer, Machine Learning     13
Senior Research Analyst                 12
Name: count, dtype: int64

In [20]:
jobs['location'].value_counts().head(20)
# The most common job locations in the dataset

location
Seattle, WA            563
New York, NY           508
Cambridge, MA          487
Boston, MA             454
San Francisco, CA      425
San Diego, CA          294
Chicago, IL            292
Boulder, CO            233
Washington, DC         230
Sunnyvale, CA          221
Mountain View, CA      199
Los Angeles, CA        187
Austin, TX             156
Atlanta, GA            147
Redmond, WA 98052      117
Cambridge, MA 02139     95
Seattle, WA 98109       95
New York, NY 10016      83
San Diego, CA 92121     71
Cambridge, MA 02142     64
Name: count, dtype: int64

In [21]:
jobs['company'].value_counts().head(20)
# The most common companies in the dataset

company
Amazon.com                                358
Ball Aerospace                            187
Microsoft                                 137
Google                                    134
NYU Langone Health                         77
Fred Hutchinson Cancer Research Center     70
KPMG                                       66
Lab126                                     50
Facebook                                   49
Broad Institute                            49
Walmart eCommerce                          45
McKinsey & Company                         41
Takeda Pharmaceutical                      39
Harnham                                    39
University of Washington                   39
Celgene Corporation                        34
Oath Inc                                   34
Pharmacyclics, an Abbvie Company           34
Cymer                                      32
Brigham & Women's Hospital(BWH)            31
Name: count, dtype: int64

In [ ]:
jobs['description'].iloc[0]
# Are the descriptions in sentences or just keywords? Let's check the first one.

"Development Director\nALS Therapy Development Institute has an immediate opening for Development Directors. Reporting directly to the Senior Development Director, the Development Director at ALS TDI is a senior fundraising position working to identifying potential prospects and cultivating solicitation strategies and in closing asks with donors including individuals and corporations by building networks via events, generating awareness of ALS TDI; outreach including attending and speaking at events as well as personally cultivates relationships with patients, prospects and donors. This position will be responsible for generating and managing a portfolio of at least two million to five million dollars per year. This position will be located in Atlanta, GA.\n\nRequirements:\nBachelor's Degree requiredMinimum 6-8 years' experience in fundraising and business developmentSuccessful track recording in fundraising with major donors or scientific sales preferredDemonstrated ability to work independently and make progress on several prospects/projects at the same time.Excellent English oral, written and presentation skillsStrong leadership and management skills, as well as the ability to forge strong interpersonal relationshipsAbility to travelExcellent computer skills including use of word processing, spreadsheet, database, presentation and prospect management software operating off a PC-based system including Salesforce.\nAbout ALS Therapy Development Institute (ALS.net)\n\nThe ALS Therapy Development Institute (ALS.net) and its scientists actively discover and develop treatments for ALS. ALS.net is the world's first and largest nonprofit biotech focused 100% on ALS research. Led by ALS patients and their families, the charity understands the urgent need to slow and stop this horrible disease. ALS.net, based in Cambridge, MA, has served as one of the leaders in sharing data and information with academic and ALS research organizations, patients and their families. For more information, visit www.als.net.\n\nTo Apply\nPlease apply at https://als.applicantpro.com. Please include a cover letter, salary requirements and resume. No phone calls please.\nALS TDI is an equal opportunity employer."

In [28]:
jobs['description'].iloc[1]

'Job Description\n\n"The road that leads to accomplishment is narrow." -Desmond\nOstentatious is a strong adjective that fits the description of an individual that inhibits the natural and innate spirit of vivaciousness, vigor and the eager characteristics that comprise the disposition of one who\'s willing to learn; to take on the attitude of "the eternal student".\nWith that said, Atlanta, Georgia-based scientific R&amp;D outfit, Hexagon Lavish®, has an open position for an excitable principal research assistant that will be mentored and guided by our Chief Science Officer.\nThis position includes computational and statistical analysis of sequencing studies, technical and logistical collaboration with international consortia. As well, the Excitable Principal Research Assistant will be responsible for setting the schedule for entry-level scientists whom will also be guided by our Chief Scientist. The Excitable Principal Research Assistant will also be in charge of delegating reports and responsibilities to the Project Leads on behalf of the Chief Science Officer and the Chief Technology Officer.\nThe Excitable Principal Research Assistant will engage entry-level scientists and researchers, setting-up work schedules for entry-level scientists and researchers and also be heavily-involved in workshops and internal team seminars as well as perform clerical and/or administrative duties such as reports that are directly to be addressed to the Chief Science Officer.\n*** A solid background in constructive optics algorithms combined with expansive computer vision and image inferential is the most preferable candidacy. *** Qualifications\n\nIntegrating data across formats and sources by robust synchronization with existing datasets and databases\n\nUnder general direction, developing innovative analytical methods to enable collaborators to interpret and design follow-up research\n\nProviding support to internal team members across all interdisciplinary backgrounds\n\nLead and contribute to manuscript preparation as well as internal and external project-team reports\n\nActively participating in project team and group meetings\nAdditional Information\n\nEssential Job Functions\nPh.D. in Computer Science, Mathematics, Statistics, Chemistry, or other quantitative discipline required\n\n5+ years experience, with varying datasets and experience with Computational Biology/Statistics/Physics, Mathematics, Computer Science, Algorithms/Incorporate Learning, etc.\n\nRelevant experience or formal training in laboratorial and/or clinical research\n\nMust have demonstrable proficiency with several standard computational languages and also some form of "esoteric programming"\n\nFamiliarity with image inferential analysis tools\n\nFamiliarity with a range of optics algorithm tools\n\nThorough understanding of statistics preferred\n\nApplication of modeling and software expertise for analysis of complex R&amp;D efforts\n\nConduct feasibility studies to provide technical assessment of proposed research\n\nPreparation of briefing materials, research announcements, and technical reports\n\nTechnical monitoring of R&amp;D efforts for adherence to statement of work (SOW) tasks, program milestones, and deliverables\n\nParticipation in program reviews/site visits/field tests and coordination of scientific workshops as required\n\nSummarize and communicate the intellectual content of scientific and technological information to both scientific and non-scientific audiences\n\nInteract with stakeholders from multiple disciplines including engineering, biology, neuroscience, clinical, regulatory and policy teams\n\nDemonstrable mastery of high-performance computing of the low-level, high-performance development skills needed to perform research on distributed, highly scalable architectures conducive to the evolving nature of PIR\n\nOther Essential Job Functions\nSound decision-maker\n\nEstablish effectiveness as a mentor\n\nBe contributory to the scientific endeavors of the company\n\nOther Skills/Abilities\nExcellent communication skills, both verbally and in written form\n\nFluent in English\n\nStrong interpersonal skills\n\nMust demonstrate a high degree of integrity, trustworthiness, respect for others and the ability to deal appropriately with confidential and sensitive information\n\n Must demonstrate an understanding and acceptance of Hexagon Lavish®’s mission, vision and values\n\nHexagon Lavish® is an equal opportunity employer'

In [29]:
jobs['description'].iloc[2]

'Growing company located in the Atlanta, GA area is currently looking to add a Data Scientist to their team. The Data Scientist will analyze business level data to produce actionable insights utilizing analytics tools and languages, etc. R, Python and/or C++: The Data Scientist will serve as the organization’s leader, helping to grow their data science initiative from a green state. The Data Scientist will also be responsible for advancement of analytical projects from inception to delivery and beyond.\nRESPONSIBLITIES;\n 1. Leverage Big Data to discover patterns and solve strategic and tactical business problems using massive structured and unstructured data sets across multiple environments\n 2. Develop analytical capabilities (modeling and processes) that drive better outcomes for both customers and the company\n 3. Drive the collection, cleansing, processing and analysis of new and existing data sources.\n 4. Research industry topics impacting opportunities relevant for data analysis projects\n 5. Execute complex analyses to aid in reporting and interpretation of analytical findings to build a comprehensive solution.\n 6. Demonstrates good judgment and analytical skills to conduct option analysis and present recommendations\n 7. Support and resolve issues related to analyses or deliverable in production\n 8. Works with internal and external clients to understand, clarify, and analyze requirements to understand the business, and potential, impactful solutions\n 9. Mapping of processes to understand opportunities for advanced analytics and product enhancement\n\n\nRequirements:\n5. 1. BA/BS Degree in Business Analysis, Computer Science, Economics, Data Science. Masters degree preferred\n 2. 5+ years of Predictive Analytics, Statistical Modeling, Machine Learning a plus\n 3. Expect level understanding of analytics tools and language (R, Python, or C++ etc.)\n 4. Experienced in Business Analysis, requirement definition\n 5. Proven and recent experience working with Sales, Marketing, Supply Chain, and/or Manufacturing Data\n 6. Able to navigate and access structured and unstructured data environments (i.e. Hadoop, Oracle, SQL etc)\n 7. Experience utilizing internal and external data sources to identify otherwise hidden industry trends to impact product development\n 8. Exposure to visualization tools, Tableau/QlikSense\n 9. Must be solution-oriented and focused on innovation.\n 10. Familiar with scripting language: e.g. Perl, Python or a programming language: e.g. Java\n \n\nTo express interest in this position, please Email Resume in MS-Word or .pdf format and attach cover letter with Salary requirements and contact information. Please be sure to reference Job #2093.\n NO SPONSORSHIP AVAILABLE!\n\n\nLocation: Atlanta, GA\n\nType: Permanent\n\nSalary: $$,$$$ / DOE'

In [ ]:
jobs['position'].sample(20, random_state=42)
# Checking a random sample of 20 job positions to see the variety in the dataset

1335                       Customer Facing Data Scientist
5678    Machine Learning Scientist - Prime Video Homep...
6007                                  Lead Data Scientist
37                                       Health Scientist
5636                                  Principal Scientist
101                  Supply Chain Data Science Consultant
6288                    Clinical Operations, Data Analyst
2418    Postdoctoral Scientist (Cancer Institute - Imm...
2183                               Analyst - Optimization
1042                           Senior Full Stack Engineer
4239               Data Scientist for Technology Start-Up
4060    GSAM Technology - Data Science and Machine Lea...
132                                             Ecologist
1074    Supply Chain Research Analyst, Aerospace and D...
1918                     Data Scientist - TS/SCI Required
642     Engineering Aide III - Mission & Process Analy...
5015    Applied Scientist - Personalization Data Sciences
2191                  Postdoctoral Scientist (Immunology)
4152                                        Data Engineer
6124                                Senior Food Scientist
Name: position, dtype: str

In [52]:
#Overall skill demand analysis
skills = ["sql", "python", "microsoft excel", "tableau", "power bi", "aws", "azure", "spark", "hadoop", "machine learning", "deep learning", "statistics", "pytorch", "snowflake", "sas", "tensorflow", "databricks"]
# A list of common data skills to check for in the job descriptions
results = []
for skill in skills:
    count = jobs['description'].str.lower().str.contains(skill, na=False).sum()
    
    results.append({"skill": skill, "count": count})

# Counting how many job descriptions mention each of the common data skills
skills_df = pd.DataFrame(results)
skills_df= skills_df.sort_values(by='count', ascending=False)
print(skills_df)
skills_df.to_csv('../data/overall_skills_demand.csv', index=False)
# Displaying the counts of each skill in descending order

               skill  count
1             python   2852
9   machine learning   2452
11        statistics   2110
0                sql   1924
5                aws   1133
7              spark   1006
8             hadoop    925
14               sas    853
10     deep learning    592
3            tableau    492
15        tensorflow    407
6              azure    251
12           pytorch    126
2    microsoft excel    117
4           power bi     41
13         snowflake     20
16        databricks     16

In [39]:
def categorize_role(title):
    if not isinstance(title, str):
        return "Other"
    
    title = title.lower()
    if "scientist" in title:
        return "Data Scientist"
    elif "analyst" in title:
        return "Data Analyst"
    elif "engineer" in title:
        return "Data Engineer"
    else:
        return "Other"
jobs['role_category'] = jobs['position'].apply(categorize_role)
# Creating a new column to categorize job roles into Data Scientist, Data Analyst, Data Engineer,

In [40]:
jobs['role_category'].value_counts()
# Checking the counts of each role category in the dataset

role_category
Data Scientist    2645
Other             2249
Data Engineer     1217
Data Analyst       853
Name: count, dtype: int64

In [53]:
# Skill Demand by Role Category
results = []
roles = ["Data Scientist", "Data Analyst", "Data Engineer"]
for role in roles:
    subset = jobs[jobs['role_category'] == role]

    for skill in skills:
        pct = subset['description'].str.lower().str.contains(skill, na=False).mean()

        results.append({"role": role, "skill": skill, "percentage": pct * 100})
skill_role_df = pd.DataFrame(results)
print(skill_role_df)
# Calculating the percentage of job descriptions that mention each skill for each role category
skill_role_df.to_csv('../data/skills_by_role.csv', index=False)

              role             skill  percentage
0   Data Scientist               sql   31.758034
1   Data Scientist            python   53.459357
2   Data Scientist   microsoft excel    1.096408
3   Data Scientist           tableau    8.128544
4   Data Scientist          power bi    0.378072
5   Data Scientist               aws   14.782609
6   Data Scientist             azure    2.570888
7   Data Scientist             spark   19.735350
8   Data Scientist            hadoop   17.844991
9   Data Scientist  machine learning   49.262760
10  Data Scientist     deep learning   12.967864
11  Data Scientist        statistics   44.461248
12  Data Scientist           pytorch    2.797732
13  Data Scientist         snowflake    0.189036
14  Data Scientist               sas   13.875236
15  Data Scientist        tensorflow    8.544423
16  Data Scientist        databricks    0.189036
17    Data Analyst               sql   34.818288
18    Data Analyst            python   26.846424
19    Data Analyst   microsoft excel    6.799531
20    Data Analyst           tableau   15.123095
21    Data Analyst          power bi    1.641266
22    Data Analyst               aws    9.847597
23    Data Analyst             azure    0.820633
24    Data Analyst             spark    3.634232
25    Data Analyst            hadoop    3.634232
26    Data Analyst  machine learning    9.730363
27    Data Analyst     deep learning    0.468933
28    Data Analyst        statistics   34.818288
29    Data Analyst           pytorch    0.000000
30    Data Analyst         snowflake    0.351700
31    Data Analyst               sas   20.164127
32    Data Analyst        tensorflow    0.000000
33    Data Analyst        databricks    0.351700
34   Data Engineer               sql   33.032046
35   Data Engineer            python   56.368118
36   Data Engineer   microsoft excel    0.246508
37   Data Engineer           tableau    3.533279
38   Data Engineer          power bi    0.493016
39   Data Engineer               aws   27.280197
40   Data Engineer             azure    9.120789
41   Data Engineer             spark   25.718981
42   Data Engineer            hadoop   23.171734
43   Data Engineer  machine learning   44.207067
44   Data Engineer     deep learning    9.860312
45   Data Engineer        statistics   12.489729
46   Data Engineer           pytorch    2.711586
47   Data Engineer         snowflake    0.739523
48   Data Engineer               sas    4.930156
49   Data Engineer        tensorflow    9.531635
50   Data Engineer        databricks    0.410846

In [ ]:
analyst_jobs= jobs[jobs['role_category'] == "Data Analyst"]
# Creating a subset of the dataset for Data Analyst roles
analyst_jobs.value_counts('position').head(20)
# The most common Data Analyst job positions in the dataset

for analyst in analyst_jobs['position'].unique():
    print(f"Skills mentioned in {analyst} job descriptions:")
    subset = analyst_jobs[analyst_jobs['position'] == analyst]
    for skill in skills:
        pct = subset['description'].str.lower().str.contains(skill, na=False).mean()
        print(f"{skill}: {pct * 100:.2f}%")
    print("\n")
# For each unique Data Analyst job position, calculating the percentage of job descriptions that mention each skill

Skills mentioned in Data Analyst job descriptions:
sql: 86.36%
python: 63.64%
microsoft excel: 4.55%
tableau: 40.91%
power bi: 9.09%
aws: 22.73%
azure: 9.09%
spark: 18.18%
hadoop: 18.18%
machine learning: 27.27%
deep learning: 0.00%
statistics: 31.82%
pytorch: 0.00%
snowflake: 0.00%
sas: 22.73%
tensorflow: 0.00%
databricks: 4.55%


Skills mentioned in Analyst - CIB Credit Research job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in STATISTICAL FORECAST ANALYST job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Business Intelligence Data Science Analyst - Supply Chain job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 100.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Statistical Analyst job descriptions:
sql: 50.00%
python: 33.33%
microsoft excel: 0.00%
tableau: 16.67%
power bi: 16.67%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 66.67%
pytorch: 0.00%
snowflake: 0.00%
sas: 83.33%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Statistical Quantitative Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Research Analyst job descriptions:
sql: 10.94%
python: 6.25%
microsoft excel: 7.81%
tableau: 4.69%
power bi: 0.00%
aws: 4.69%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 14.06%
pytorch: 0.00%
snowflake: 0.00%
sas: 6.25%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Analyst, Research job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Quantitative Analyst job descriptions:
sql: 66.67%
python: 71.43%
microsoft excel: 0.00%
tableau: 9.52%
power bi: 0.00%
aws: 4.76%
azure: 0.00%
spark: 0.00%
hadoop: 4.76%
machine learning: 4.76%
deep learning: 0.00%
statistics: 47.62%
pytorch: 0.00%
snowflake: 0.00%
sas: 14.29%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in DATA ANALYST SUPPLY CHAIN job descriptions:
sql: 100.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Quantitative Finance Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Advertiser Research Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Research Informatics Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Enterprise Data Analyst & Data Engineer job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in 2018 - Health Research Analyst 2 - New job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Quantitative Finance Analyst/C++ Developer job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Coding Research Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Business Intelligence Analyst, People Analytics & Measurement job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Vendor Research Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Sponsored Research Financial Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in BI Quantitative Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Corporate Investment Quantitative Finance Analyst job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Malware Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Market Research Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 20.00%
tableau: 0.00%
power bi: 0.00%
aws: 6.67%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 13.33%
pytorch: 0.00%
snowflake: 0.00%
sas: 6.67%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Business Intelligence Analyst job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 33.33%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 33.33%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Marketing Research Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Analyst, Payments Study - GC Insights, New Ventures job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 100.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Analyst - Multi-client Benchmarks, GC Insights - New Ventures job descriptions:
sql: 100.00%
python: 0.00%
microsoft excel: 100.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in BI - Analytics - Cloud Platform Operations Analyst job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 100.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Sr Quantitative Finance Analyst/C++ Developer job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Research Analyst and Team Lead - HR Insights - Bersin job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Analyst - Marketing Research job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Analyst - GC Insights, New Ventures job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 100.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Market Research Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Computer Network Defense (CND) Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Operations Research Analyst (contractor role) job descriptions:
sql: 100.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in SR DATA ANALYST SUPPLY CHAIN job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Compensation and HRIS Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 100.00%
tableau: 0.00%
power bi: 0.00%
aws: 100.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Sr Quantitative Finance Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Sr. Market Research Analyst job descriptions:
sql: 50.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 50.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 50.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in GIS Analyst and Research Associate job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Operations Analyst, Omni job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Analyst - Public Education Data Analysis job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Research Analyst In-House Counsel job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Quantitative Analyst job descriptions:
sql: 28.57%
python: 42.86%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 14.29%
deep learning: 0.00%
statistics: 57.14%
pytorch: 0.00%
snowflake: 0.00%
sas: 28.57%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Medical Research Specialist - Policy Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Quantitative Data Analyst job descriptions:
sql: 50.00%
python: 50.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 50.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Quantitative Analyst - Bank Financial Risk job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Research Analyst - Advanced Analytics job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 100.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Medical Research Specialist - Polcy Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Credit Research Analyst job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Project Analyst job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 100.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Compliance Quantitative Data Analyst job descriptions:
sql: 100.00%
python: 0.00%
microsoft excel: 100.00%
tableau: 100.00%
power bi: 0.00%
aws: 100.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Analyst Disaster Recovery Implementation job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 100.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Research Analyst job descriptions:
sql: 16.67%
python: 0.00%
microsoft excel: 8.33%
tableau: 16.67%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 41.67%
pytorch: 0.00%
snowflake: 0.00%
sas: 16.67%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Quantitative Marketing Analyst job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 50.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Data Warehouse Analyst job descriptions:
sql: 100.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 100.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 100.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%



In [62]:
analyst_jobs.value_counts('location').head(20)
# The most common locations for Data Analyst jobs in the dataset

location
New York, NY            106
Chicago, IL              69
Washington, DC           68
Boston, MA               57
San Francisco, CA        51
Los Angeles, CA          46
Seattle, WA              36
Atlanta, GA              25
Austin, TX               22
Cambridge, MA            20
New York, NY 10016       18
Manhattan, NY            16
Washington, DC 20001     13
San Diego, CA            13
Sunnyvale, CA            10
Boulder, CO               9
Mountain View, CA         7
Chicago, IL 60606         6
Washington, DC 20036      6
New York, NY 10036        6
Name: count, dtype: int64

In [63]:
analyst_jobs['company'].value_counts().head(20)

company
Bank of America                16
NYU Langone Health             14
Google                         11
McKinsey & Company             10
Amazon.com                     10
BNY Mellon                      9
JLL                             9
The Boston Consulting Group     9
Leidos                          8
Uber                            8
State Street                    7
University of Washington        7
DigitasLBi                      6
The Camstoll Group              6
JUUL Labs                       6
ICF                             5
Mathematica Policy Research     5
The University of Chicago       5
Kantar Millward Brown           5
Nielsen                         5
Name: count, dtype: int64

In [ ]:
scientist_jobs= jobs[jobs['role_category'] == "Data Scientist"]

scientist_jobs.value_counts('position').head(20)
# The most common Data Scientist job positions in the dataset

for scientist in scientist_jobs['position'].unique():
    print(f"Skills mentioned in {scientist} job descriptions:")
    subset = scientist_jobs[scientist_jobs['position'] == scientist]
    for skill in skills:
        pct = subset['description'].str.lower().str.contains(skill, na=False).mean()
        print(f"{skill}: {pct * 100:.2f}%")
    print("\n")
# For each unique Data Scientist job position, calculating the percentage of job descriptions that mention each skill

Skills mentioned in An Ostentatiously-Excitable Principal Research Assistant to Chief Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Scientist job descriptions:
sql: 61.54%
python: 80.06%
microsoft excel: 0.85%
tableau: 13.11%
power bi: 0.85%
aws: 16.52%
azure: 2.28%
spark: 33.90%
hadoop: 30.20%
machine learning: 75.78%
deep learning: 12.25%
statistics: 65.24%
pytorch: 1.71%
snowflake: 0.85%
sas: 22.51%
tensorflow: 8.26%
databricks: 0.00%


Skills mentioned in Junior to Mid-level Engineer, Geologist or Environmental Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 100.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Associate - Cognitive Data Scientist Natural Language Processing job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 100.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Health Scientist III-CPTS job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Associate, Data Scientist job descriptions:
sql: 28.57%
python: 28.57%
microsoft excel: 0.00%
tableau: 28.57%
power bi: 0.00%
aws: 28.57%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 71.43%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Assistant Scientist (AR) SOM job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in DATA SCIENTIST - Supply Chain job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Scientist, Keying & Linking job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Scientist 1 – AP Forensics Team job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Scientist - ICL job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Scientist, Online job descriptions:
sql: 100.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 100.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 100.00%
databricks: 0.00%


Skills mentioned in Data Scientist - CONSULTANT Level - ORLANDO FLORIDA - We will help Relocate job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 100.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Data Scientist job descriptions:
sql: 67.71%
python: 87.50%
microsoft excel: 1.04%
tableau: 14.58%
power bi: 2.08%
aws: 16.67%
azure: 3.12%
spark: 36.46%
hadoop: 30.21%
machine learning: 78.12%
deep learning: 12.50%
statistics: 68.75%
pytorch: 3.12%
snowflake: 1.04%
sas: 21.88%
tensorflow: 13.54%
databricks: 1.04%


Skills mentioned in Business Intelligence Data Scientist - Supply Chain job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 100.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Entry Level/Junior-Level Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Scientist - Data Analysis job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Health Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in DATA SCIENTIST - SPACE OPTIMIZATION job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Manager - Data Scientist ! Orlando! job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 100.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 100.00%
databricks: 0.00%


Skills mentioned in Scientist II job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Lead Data Scientist job descriptions:
sql: 70.97%
python: 83.87%
microsoft excel: 0.00%
tableau: 16.13%
power bi: 0.00%
aws: 32.26%
azure: 6.45%
spark: 41.94%
hadoop: 35.48%
machine learning: 80.65%
deep learning: 32.26%
statistics: 70.97%
pytorch: 3.23%
snowflake: 0.00%
sas: 16.13%
tensorflow: 22.58%
databricks: 0.00%


Skills mentioned in Data Scientist - Consultant Level - Orlando, Florida - we will assist with relocation job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 100.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Chief Deep Learning Scientist job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 100.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 100.00%
databricks: 0.00%


Skills mentioned in Supervisory Health Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Manager - Cognitive Data Scientist Natural Language Processing job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 100.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Director, Data Scientist job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in VP, Data Scientist- Atlanta, GA; Charlotte, NC job descriptions:
sql: 100.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 100.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Lead Decision Scientist job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Scientist I - Sensory Panel Leader job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Scientist or Data Scientist Lead PS10268 job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 100.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 100.00%
databricks: 0.00%


Skills mentioned in Senior Cyber Security Data Scientist job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 100.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Scientist II/Ecologist II job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Manager, Data Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Machine Learning / Artificial Intelligence Research Scientist job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 100.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 100.00%
databricks: 0.00%


Skills mentioned in Research Scientist job descriptions:
sql: 0.00%
python: 43.33%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 10.00%
azure: 0.00%
spark: 6.67%
hadoop: 10.00%
machine learning: 40.00%
deep learning: 13.33%
statistics: 46.67%
pytorch: 3.33%
snowflake: 0.00%
sas: 10.00%
tensorflow: 6.67%
databricks: 0.00%


Skills mentioned in Environmental Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 20.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Scientist, Asst Bioinformatics job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Scientist, Asst (AR) SOM job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Director, NLP Data Scientist job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Senior Associate, Data Scientist (NLP/AI) job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Sr Scientist II, Analytical Science job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in HIV Research Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Azure Data Scientist, Manager job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 100.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Associate Scientist, SOM job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Director, Financial Services - Data Scientist job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Regulatory Labeling, Advertising and Promotion Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Product Development Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Research Scientist I job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 33.33%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Data Scientist - Senior Consultant - Orlando, Florida job descriptions:
sql: 100.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 100.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Lead R & D Engineer/Scientist job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 100.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Manager, Data Scientist (ML/NLP) -- Financial Services job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 100.00%
hadoop: 100.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Staff Research Scientist VII: Informational Interpretation Researcher job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 100.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Scientist, Asst (AR) School Of Medicine (SOM) job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Entry Level Geologist, Engineer or Environmental Scientist job descriptions:
sql: 0.00%
python: 0.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 100.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 0.00%
deep learning: 0.00%
statistics: 0.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 0.00%
tensorflow: 0.00%
databricks: 0.00%


Skills mentioned in Director, Data Scientist -- Financial Services/Insurance job descriptions:
sql: 0.00%
python: 100.00%
microsoft excel: 0.00%
tableau: 0.00%
power bi: 0.00%
aws: 0.00%
azure: 0.00%
spark: 0.00%
hadoop: 0.00%
machine learning: 100.00%
deep learning: 0.00%
statistics: 100.00%
pytorch: 0.00%
snowflake: 0.00%
sas: 100.00%
tensorflow: 0.00%
databricks: 0.00%



In [67]:
jobs[
    jobs['role_category'] == "Other"
]['position'].sample(20, random_state=42)
# Checking a random sample of 20 job positions that were categorized as "Other" to see

6822                                        Manager, TPMs
1478                         Statistical Arbitrage Trader
5321    Senior Manager for Automated Profitability Man...
768     Medical Director/Sr Medical Director - Neurolo...
4932                     Principal Statistical Programmer
2584       Manager, Machine Learning Data Science - Alexa
5089                                   Data Coordinator I
2808                                 Global Safety Sr Mgr
3664                       Electron Microscopy Technician
4854                       Principal Functional Architect
940        Senior Product Manager, Sort & Recommendations
4439    Full-time PhD opportunities for students & rec...
4085       Data Reporting Developer (Python) - Accounting
3406               Technical Program Manager, AR Platform
3756                                  Research Assistants
6202                Associate Director, Data and Analysis
5574                                    Community Manager
6017      Presales Solutions Architect | Machine Learning
3872    Program Planner , Bureau of HIV/AIDS Preventio...
4745    Senior Manager, Manufacturing Technical Servic...
Name: position, dtype: str